### ISSUE TITLE
Replace RavenDB servers with cloud.ravendb.net

### ISSUE THREAD

**Issue by afifmohammed** [Remitter/Discuss#1]
RavenDb cloud has a new [offering](https://cloud.ravendb.net/) from the mothership. It's available in Azure, and running the latest tech. We probably are not at the point where performance gains that come with bare metal are needed. 

Considering we aspire to have the current production version for the majority looked after by a team that have not been on the journey from the start, this is probably a good step in reducing all the things that can wrong with a team managing their own DB servers. 

Off the bat would be keen to understand if everything else was equal, what's involved in swapping to managed servers via this offering. How transparent is this change to the code and what's involved in testing it.

**Comment by jpv001** [comment]
We'd need to move to Raven 4 first as 3.5 isn't offered on that platform, but it is a really attractive option for 4 hosting. We have some pretty strict requirements for compliance and monitoring, They'd need to be PCI Tier 1 certified as well. I think once we understand the 4 jump this is how we could facilitate that move

**Comment by afifmohammed** [comment]
I am going to close this as per @jpv001's comment earlier.
